### ISSUE TITLE
Failure

### ISSUE THREAD

**Issue by tilllt** [dword1511/raspiraw#1]
/rpi2dng ../scans/rawtest/01150.jpg

../scans/rawtest/01150.jpg:
Model: RP_imx219
Found RAW data @ offset 4093445.
Creating ../scans/rawtest/01150.dng...
Using color matrix:
        0.9596  -0.3092 -0.0674
        -0.2108 1.0000  -0.2059
        0.0538  -0.4147 0.9440
TIFFWriteDirectoryTagIfdIfd8Array: Attempt to write value larger than 0xFFFFFFFF in Classic TIFF file..
../scans/rawtest/01150.dng: Failed to allocate memory for to read TIFF directory (0 elements of 12 bytes each).
TIFFReadDirectory: Failed to read directory at offset 8.
../scans/rawtest/01150.dng: Failed to allocate memory for to read TIFF directory (0 elements of 12 bytes each).
TIFFReadDirectory: Failed to read directory at offset 8.
TIFFSetField: ../scans/rawtest/01150.dng: Unknown tag 34665.
Extracting RAW data...
TIFFWriteEncodedStrip: Must set "ImageWidth" before writing data.
Error writing TIFF stripe at row 0.

**Comment by dword1511** [comment]
Can you provide a file that causes the same problem?
By the way, I was planning to get rid of `libtiff` when I have time. It messes up EXIF rationals quite badly.

**Comment by tilllt** [comment]
Sure, here is one

https://cloud.n0ne.de/s/6oRyWSFLTpZ5AGS

**Comment by dword1511** [comment]
Are you running this thing on a Pi? I did not realize that it won't work on 32-bit machines. https://github.com/dword1511/raspiraw/commit/f4b7add039614e8420cdb4a6fb47a8c2e58f1499 should have fixed it.

**Comment by tilllt** [comment]
Hmm it's a rpi4 and I installed rasbian lite, I don't think there should be anything 32bit involved - or IS the default rpi distro still 32Bit?

**Comment by tilllt** [comment]
Thanks for looking into this

**Comment by tilllt** [comment]
Interestingly, the picture from the RAW to DNG converter (Right) looks LESS sharp then the JPG version (Left). I wonder if there is some sharpening done in the JPG or of the DNG conversion (Irfanview Plugin) is not really good...

![Clipboard](https://user-images.githubusercontent.com/1854364/80304542-07550a00-87b7-11ea-984e-1e77f3cdb2d9.jpg)

**Comment by dword1511** [comment]
Normally the ISP does chromatic aberration correction as well as some sharpening, so the processed should look sharper than RAW. You would need to do the same for DNG.

I normally would use `darktable` to process RAW images.
